loader:
  class_path: smileval.loaders.mcq.MCQQuestionLoader
  init_args:
    input_file_path: test5.csv
    use_example: false
    use_shuffle: true

model:
#  class_path: smileval.models.ollama.OllamaChatCompletionModel
  class_path: smileval.models.openai.OpenAIChatCompletionModel
  init_args:
    name: "na" # :8b-instruct-fp16
    # ensures we don't artifically run out of context
    spoof_api_name: "gpt-4-32k"
    api_key: "sk-example"

seed: 69424269
parallel: 1
options:
  class_path: smileval.models.ChatCompletionOptions
  dict_kwargs:
    use_system_prompt_workaround: false
    stop_tokens_2:
      - "\n"
      # phi moment
      - "<|end|>"
      - "<|eot_id|>"
    # command R broken in llama.cpp moment
    stop_tokens:
      - "<|im_end|>"